import Head from "next/head";
import Image from "next/image";
import { Field, Form, Formik } from "formik";
import InputField from "../components/InputField";
import TextField from "../components/textField";
import * as Yup from "yup";

const productSchema = Yup.object({
  productName: Yup.string()
    .max(35, "max length is 35")
    .required("this field is required"),
  productPrice: Yup.number("it must be a number")
    .required("this field is required")
    .positive("no negative numbers allowed"),
  productDescription: Yup.string().required("this field is required"),
});
export default function Home() {
  //create mutation to add the product prices invalidate query on create
  //create query to get the values //prefetch the data for ssr
  //create mutation to update the value and invalidate also
  //create mutation to delete the value and invalidate also
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen  flex flex-col md:grid grid-cols-2 font-mono \">
        <section className="col-start-1 h-screen p-2 flex flex-col gap-2">
          <h1 className="text-5xl text-white p-3 font-bold text-center bg-pink-600 rounded-md mt-2">
            Crud App
          </h1>
          <section className="flex-grow">
            <Formik
              initialValues={{
                productName: "",
                productPrice: "",
                productDescription: "",
              }}
              onSubmit={(values, { resetForm, setSubmitting, ...actions }) => {
                console.log(actions);
                actions.setErrors({
                  productName: "hamobozo",
                });
                resetForm();
              }}
              validationSchema={productSchema}
            >
              {({ errors, touched, ...props }) => (
                <Form className="bg-purple-800 font-semibold rounded-md flex flex-col h-full gap-5 p-4 justify-center">
                  <InputField
                    id="product-name"
                    name="productName"
                    className="rounded-lg shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  />

                  <InputField
                    id="product-price"
                    name="productPrice"
                    className="rounded-lg shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  />
                  <TextField
                    name="productDescription"
                    id="product-description"
                    className="rounded-lg shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  />
                  <button
                    className="rounded-lg text-white shadow-sm bg-pink-600 py-3 px-3 hover:bg-pink-800 visited:bg-pink-500  focus:border-indigo-500 focus:ring-indigo-500 "
                    type="submit"
                  >
                    Submit
                  </button>
                  <button
                    className="rounded-lg text-white shadow-sm bg-pink-600 py-3 px-3 hover:bg-pink-800 visited:bg-pink-500  focus:border-indigo-500 focus:ring-indigo-500 "
                    type="reset"
                  >
                    Reset
                  </button>
                  <div className="overflow-auto">{JSON.stringify(props)}</div>
                </Form>
              )}
            </Formik>
          </section>
        </section>
        <section className="col-start-2 h-screen bg-slate-800 p-2 rounded-md">
          
        </section>
      </main>
    </>
  );
}
